baseURL = 'https://sethgame.github.io/'
languageCode = 'en'
title = 'Seth Eom'
theme = 'hugo-bearblog'
[pagination]
pagerSize = 5
summaryLength = 30
[params]
description = 'Seth - Computer Engineering Student & AI Researcher'
author = 'Seth Eom'
[markup.goldmark.renderer]
unsafe = true
